remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Shreyas' personal blog
description: This is where I share some random musings
author: Shreyas Parekh
